// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://usjfkgbdlwnhnofenkmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzamZrZ2JkbHduaG5vZmVua21qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMTMzNDksImV4cCI6MjA3Mjc4OTM0OX0.4L7xWY1fB8tDtZKwsQy05TBGJ3Sw4aEJtfx_CWJw9N4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});